---
title: "Untitled"
author: "Alexandra Nosal"
date: "11/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
```

```{r}
ICPMS_merged_tidy_data <- read_csv("ICPMS_merged_tidy_data.csv")
View(ICPMS_merged_tidy_data)
```


```{r}
sample_sites <- unique(filter(ICPMS_merged_tidy_data, Site != "MB", Site != "")$Site)
sample_sites
```

```{r}
metals_analyzed <- unique(ICPMS_merged_tidy_data$metal)
metals_analyzed
```

```{r}
ICPMS_cal <- NULL
for (unique_metal in metals_analyzed){
  cal <- ICPMS_merged_tidy_data %>%
    filter(Type == "Cal1" | Type == "Cal2" | Type == "Cal3") %>%
    filter(metal == unique_metal) %>%
    select(Concentration, CPS, RSD)
  w <- 1/(cal$CPS*cal$RSD)^2
  model <- lm(cal$CPS ~ cal$Concentration, weights = w)
  slope <- model$coefficients[2]
  intercept <- model$coefficients[1]
  slope_std <- summary(model)$coefficients[2,2]
  intercept_std <- summary(model)$coefficients[1,2]
  
  plot(cal$CPS ~ cal$Concentration, 
       xlab = paste("Concentration of ", unique_metal, "(ppb)"), 
       ylab = "Counts per Second")+ 
        abline(model, col = "red") +
         title(paste("Calibration for ", unique_metal))
  equation <- tibble(metal = unique_metal, slope, slope_std, intercept, intercept_std)
  ICPMS_cal <- rbind(ICPMS_cal, equation)
}

ICPMS_cal
remove(equation, cal, slope, slope_std, intercept, intercept_std, w, model, unique_metal)
```

```{r}
sample_analysis <- function(unique_site){
  concentration_data <- NULL
  for (unique_metal in metals_analyzed){
    sample <- filter(ICPMS_merged_tidy_data, metal == unique_metal, Site == unique_site)
    data <- NULL
    
    for(ID in sample$Sample.Key){
      sample_data <- filter(sample, Sample.Key == ID)
      cal <- filter(ICPMS_cal, metal == unique_metal)
      
      #Sample Analysis
      m <- cal$slope
      b <- cal$intercept
      y <- sample_data$CPS
     
       b_e <- cal$intercept_std
      m_e <- cal$slope_std
      
      x <- (y-b)/m
      
      rsd <- sample_data$RSD
      cps <- sample_data$CPS
      
      #Error Propagation
      e_yb <- sqrt((rsd)^2 + (b_e)^2)
      
      #error in y-b from the calibration
      yb <- cps-b
      e_x <- x*sqrt((e_yb/yb)^2 + (m_e/m)^2)
      
      data <- rbind(data,  data_frame(sample_key = ID,  x, e_x))
      if (unique_site  != "MB"){
        concentration_data <- data_frame(sample_key = sample_data$Sample.Key,
                                         analyst = sample_data$Analyst, 
                                         metal = unique_metal, 
                                         Site = unique_site,
                                         conc_dil = x,
                                         conc_dil_error = e_x) %>%
                              rbind(concentration_data)
      }
    }
    if (unique_site == "MB"){
        x <- mean (data$x)
        e_x <- sd(data$x)
        concentration_data <- data_frame(metal = unique_metal,
                                         Site = unique_site,
                                         conc_dil = x,
                                         conc_dil_error = e_x) %>%
                              rbind(concentration_data)
    }
  }
  return(concentration_data)
}
```


```{r}
run_sites <- function(Function){
  value <- NULL
  for(sites in sample_sites){
    site_value <- Function(sites)
    value <- rbind(site_value, value)
  }
  return(value)
}
```


```{r}
MB <- sample_analysis("MB")
uncor_sample <- run_sites(sample_analysis)

MB
uncor_sample
```


```{r}
sample_data_mb <- NULL

for (unique_metal in metals_analyzed){
  MB_metal <- filter (MB,  metal == unique_metal)
  sample_metal <- filter(uncor_sample, metal == unique_metal)
  conc_dil_blanked <- sample_metal$conc_dil-MB_metal$conc_dil
  conc_dil_blanked_error <- sqrt ((sample_metal$conc_dil_error)^2 + (MB_metal$conc_dil_error)^2)
  
  sample_data_mb <- sample_metal %>%
    mutate(conc_dil_blanked, conc_dil_blanked_error) %>%
    rbind(sample_data_mb)
}
sample_data_mb

```

Procedure:


```{r}
vol_e <- 1
mass_e <- 0.001
dil_1010_e <- sqrt(1^2 + 10^2)
dil_e <- sqrt((dil_1010_e/1010)^2+(1/10)^2)
```


```{r}
sample_data <- merge(ICPMS_merged_tidy_data, sample_data_mb) %>%
  unique() %>%
  mutate(conc_blanked = conc_dil_blanked*(Total.Volume/1000)/(Mass.of.Soil/1000)*101,
        conc_blanked_error = conc_blanked*
        sqrt((conc_dil_blanked_error/conc_dil_blanked)^2 +
               (dil_e/101)^2 +
               (mass_e/Mass.of.Soil)^2 +
               (vol_e/Total.Volume)^2),
    conc_unblanked = conc_dil*(Total.Volume/1000)/(Mass.of.Soil/1000)*101,
    conc_unblanked_error = conc_unblanked*
        sqrt((conc_dil_error/conc_dil)^2 +
               (dil_e/101)^2 +
               (mass_e/Mass.of.Soil)^2 +
               (vol_e/Total.Volume)^2)) %>%
  select(-Concentration,
         -Type,
         -Mass.of.Soil,
         -CPS,
         -RSD,
         -conc_dil_blanked,
         -conc_dil_blanked_error,
         -conc_dil,
         -conc_dil_error)
```

```{r}
rm(list = ls()[!(ls() %in% c("ICPMS_merged_tidy_data", "sample_data"))])
```

























