---
title: "Data_Tidying"
author: "Alexandra Nosal"
date: "10/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
```

```{r}
ICPMS_imported <- read.csv("~/Chemistry 313/Johnson Creek/Johnson_Creek_ICPMS/ICPMS_Data.csv", skip=1, na="N/A")
sample_key <- read.csv("~/Chemistry 313/Johnson Creek/Johnson_Creek_ICPMS/Sample_Key.csv", skip=0)
```

```{r}
ICPMS_imported
sample_key
```

```{r}
RSD_data <- ICPMS_imported %>%
  select(Cr52 = CPS.RSD, Cr53 = CPS.RSD.1, As75 = CPS.RSD.2, Cd111 = CPS.RSD.3, Cd114 = CPS.RSD.4, Pb208 = CPS.RSD.5, Ge_RSD = CPS.RSD.7, Sample.Key) %>%
  pivot_longer(1:6, names_to = "metal", values_to = "RSD")


```

```{r}
ICPMS_tidy <- ICPMS_imported %>%
  select(Cr52 = CPS, Cr53 = CPS.1, As75 = CPS.2, Cd111 = CPS.3, Cd114 = CPS.4, Pb208 = CPS.5, Ge_CPS = CPS.7, Sample.Key) %>%
  pivot_longer(1:6, names_to = "metal", values_to = "CPS") %>%
  mutate(RSD = RSD_data$RSD/RSD_data$Ge_RSD, CPS = CPS/Ge_CPS)%>%
  select(-Ge_CPS)

all(RSD_data$Sample.Key == ICPMS_tidy$Sample.Key, RSD_data$metal == ICPMS_tidy$metal)
```

```{r}
ICPMS_merged <- merge(sample_key, ICPMS_tidy)
```

```{r}
rm(list = setdiff(ls(), "ICPMS_merged"))
```









